- name: Install pre-reqs for expo
  # follow instructions from https://docs.expo.dev/get-started/installation/
  become: true
  package:
    name:
      - nodejs
      - typescript
      - git
    state: present

- name: Installing yay packages
  yay:
    name:
      - watchman-bin # takes literally forever to compile
    state: present

- name: install android studio # make sure to run it after so you can run the installation wizard
  # make sure that kvm or virualization is allowed in your bios
  yay:
    name:
      - android-studio
    state: present
