- hosts: localhost
  vars:
    github_username: "miguelcmaramara"
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{lookup('env', 'HOME')}}/.ssh/id_ed25519"
  pre_tasks:
    - name: Update pacman
      become: true
      pacman:
        update_cache: true
      when: ansible_os_family == "Archlinux"

  tasks:
    - import_tasks: tasks/core-setup.yml
    - import_tasks: tasks/ssh.yml
    - import_tasks: tasks/git.yml
    - import_tasks: tasks/neovim.yml
    - import_tasks: tasks/dotfiles.yml
