# Package dependencies: chezmoi
- name: Initiating dotfiles
  shell: "chezmoi init --force git@github.com:{{ github_username }}/dotfiles.git"

- name: Updating and applying dotfiles
  shell: "chezmoi update --force"
  tags:
    - neovim
