# Taken from ThePrimeagen/ansible. Thank you!
- name: Ensure .ssh directory exists
  file:
    dest: "{{ dest_key | dirname }}"
    mode: "0700"
    state: directory
  tags:
    - ssh

- name: Install ssh key
  copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: "0600"
  tags:
    - ssh

- name: Install ssh public key
  copy:
    src: "{{ source_key }}.pub"
    dest: "{{ dest_key }}.pub"
    mode: "0644"
  tags:
    - ssh

- name: Activating ssh agent
  shell: "eval $(ssh-agent)"
  tags:
    - ssh

- name: Adding key to ssh agent
  shell: "ssh-add {{ dest_key }}"
  tags:
    - ssh
# NOTE: Do I need to set authorized key?
