- name: Install hyprland
  become: true
  pacman:
    name:
      - hyprland
    state: present

- name: Installing Hyprland required packages
  become: true
  pacman:
    name:
      - mesa # Nouveau nvidia driver
    state: present
