#!/bin/sh
#
xrandr --output DP-3 --primary --mode 2560x1440
xrandr --output DVI-D-1 --mode 1920x1080 --right-of DP-3 --rotate right
xrandr --output HDMI-1 --mode 1920x1080 --left-of DP-3 --rotate left
